export type Env = {
  GITHUB_EVENT_PULL_REQUEST_HEAD_REF: string
  GITHUB_EVENT_PULL_REQUEST_BASE_REF: string
  GITHUB_EVENT_BEFORE: string
  GITHUB_REFNAME: string
  GITHUB_REF: string
  GITHUB_EVENT_BASE_REF: string
  GITHUB_EVENT_HEAD_REPO_FORK: string
  GITHUB_WORKSPACE: string
  GITHUB_EVENT_FORCED: string
  GITHUB_EVENT_PULL_REQUEST_NUMBER: string
  GITHUB_EVENT_PULL_REQUEST_BASE_SHA: string
}

export const getEnv = (): Env => {
  return {
    GITHUB_EVENT_PULL_REQUEST_HEAD_REF:
      process.env.GITHUB_EVENT_PULL_REQUEST_HEAD_REF || '',
    GITHUB_EVENT_PULL_REQUEST_BASE_REF:
      process.env.GITHUB_EVENT_PULL_REQUEST_BASE_REF || '',
    GITHUB_EVENT_BEFORE: process.env.GITHUB_EVENT_BEFORE || '',
    GITHUB_REFNAME: process.env.GITHUB_REFNAME || '',
    GITHUB_REF: process.env.GITHUB_REF || '',
    GITHUB_EVENT_BASE_REF: process.env.GITHUB_EVENT_BASE_REF || '',
    GITHUB_EVENT_HEAD_REPO_FORK: process.env.GITHUB_EVENT_HEAD_REPO_FORK || '',
    GITHUB_WORKSPACE: process.env.GITHUB_WORKSPACE || '',
    GITHUB_EVENT_FORCED: process.env.GITHUB_EVENT_FORCED || '',
    GITHUB_EVENT_PULL_REQUEST_NUMBER:
      process.env.GITHUB_EVENT_PULL_REQUEST_NUMBER || '',
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA:
      process.env.GITHUB_EVENT_PULL_REQUEST_BASE_SHA || ''
  }
}
