on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Start Falco
        uses: falcosecurity/falco-actions/start@<commit-sha>
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: true

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: changed-files action
        uses: ./ 

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "$SUPER_SECRET"

      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@<commit-sha>
        with:
          mode: live
          verbose: true
