on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    name: A job to say hello
    steps:
      - name: Start Falco
        uses: falcosecurity/falco-actions/start@0.1.0
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: true

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: changed-files action
        uses: ./ 

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          sleep 60
          cat /home/runner/work/.git/config

      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@0.1.0
        with:
          mode: live
          verbose: true
